[config]
schemaVersion = "0.0.1"

[package]
namespace = "ExasPaintPot"
name = "SweetkinBackOnTrack"
versionNumber = "1.0.3"
description = "The sweetkins are back on track, this time in heaven! Mod remake"
websiteUrl = "https://github.com/Exas4000/Sweetkin_back_on_track"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
MT2-Trainworks_Reloaded = "0.5.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./"

[[build.copy]]
source = "./plugin_build"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = [ "monster-train-2" ]


